.TH PAL 1 "18 October 2013"

.SH NAME

pal - Compiler for PAL language

.SH SYNOPSIS

pal [-S][-n][-a][-q][-c] infile

.SH DESCRIPTION

pal accepts a pal source file with a '.pal' extention
and compiles it to an ASC file, then launches the ASC interpreter.

.SH OPTIONS

-S Leave Asc code in file.asc instead of removing it.

-n Do not produce a program listing. Default is to produce one.

-a Do not generate run-time array subscript bounds checking.
Default is to do the checking.

-q Do not print errors to standard output. Default is to print errors.

-c Compile PAL file to asc, but do not launch ASC interpreter. Useful when 
combined with the -S option.

.SH EXIT STATUS

pal returns EXIT_SUCCESS on successful execution, and EXIT_FAILURE otherwise.

.SH AUTHORS

Sarah Anderson <sma2@ualberta.ca>, 
Marko Babic <mbabic@ualberta.ca>,
Aaron Krebs <akrebs@ualberta.ca>, 
Guanqi Huang <guanqi@ualberta.ca>,
Shihao Xu <shihao1@ualberta.ca>

.SH BUGS

The current version has severe memory leaks to do the symbol table.
Recursive function calls are not supported.
String literals with invalid escape sequences cause over-reporting of other errors

.SH SEE ALSO
yacc(1), bison(1), flex(1)
