/*
 * Module implementing writing generated ASC code to file.
 */
#include "EmitToFile.h"


/*
 * Write generated code to file.
 *
 * Parameters:
 * 	fileName: name of the .asc file to which to write.
 * Return:
 * 	0 on success,
 * 	non-zero otherwise
 */
int emitToFile(char *fileName) {
	FILE *ascfp = NULL;

	if (doNotEmit) {
		return 1;
	}

	/* open the file */
	ascfp = fopen(fileName, "w");

	/* append end-of-program stuff here (like a STOP) */
	emitComment("End of user-defined pgram");
	emitStmt(STMT_LEN, "STOP");

	/* 
	 * append pre-defined ASC code here, so that it's at the bottom
	 * of the file
	 */
	emitPreDefCode();

	/* write the emitted code to file */
	writeStmtLL(ascfp, stmts);

	/* close the file */
	if (fclose(ascfp) != 0) {
		err(EXIT_FAILURE, "File IO error.");
	}

	return 0;
}


/*
 * Emit the pre-defined ASC functions.
 */
void emitPreDefCode() {
	emitBlankLine();
	emitComment("#######################################################");
	emitBlankLine();
	emitComment("Pre-defined ASC functions to follow");
	emitBlankLine();
	emitComment("#######################################################");
	emitBlankLine();

	/* call to generated function in PreDefAsc.c */
	emitPreDefAsc();
}


/*
 * Emit anything that must be emitted before the code generated from the
 * input PAL. This includes predefined funcs and procs, constants, etc.
 */
void emitInit() {
	emitComment("ASC code generated by Yet Another CMPUT415 Compiler.");
	emitComment("May the Force be ever in your favour, Mr. Potter.");
	emitComment("CMPUT 415 - Fall 2013");
	emitBlankLine();

	/* emit pre-defined constants */
	emitPreDefConsts();
}


/*
 * Emit pre-defined constant declarations.
 */
void emitPreDefConsts() {
	Symbol *s = NULL;

	emitBlankLine();
	emitComment("#######################################################");
	emitBlankLine();
	emitComment("Pre-defined constants to follow:");
	emitBlankLine();
	emitComment("#######################################################");
	emitBlankLine();

	s = getGlobalSymbol(symbolTable, TRUE_KEY);
	if (!s) err(EXIT_FAILURE, "Pre-def constant not in symbol table");
	emitConstDecl(s);
	
	s = getGlobalSymbol(symbolTable, FALSE_KEY);
	if (!s) err(EXIT_FAILURE, "Pre-def constant not in symbol table");
	emitConstDecl(s);

	s = getGlobalSymbol(symbolTable, MAXINT_KEY);
	if (!s) err(EXIT_FAILURE, "Pre-def constant not in symbol table");
	emitConstDecl(s);
}
