/*
 * Module implementing writing generated ASC code to file.
 */
#include "EmitToFile.h"


/*
 * Write generated code to file.
 *
 * Parameters:
 * 	fileName: name of the .asc file to which to write.
 * Return:
 * 	0 on success,
 * 	non-zero otherwise
 */
int emitToFile(char *fileName) {
	FILE *ascfp = NULL;

	if (doNotEmit) {
		return 1;
	}

	/* open the file */
	ascfp = fopen(fileName, "w");

	/* append end-of-program stuff here (like a STOP) */
	// TODO
	emitComment("End of user-defined pgram");
	emitStmt(STMT_LEN, "STOP");

	/* 
	 * append pre-defined ASC code here, so that it's at the bottom
	 * of the file
	 */
	emitPreDefs();

	/* write the emitted code to file */
	writeStmtLL(ascfp, stmts);

	/* close the file */
	if (fclose(ascfp) != 0) {
		err(EXIT_FAILURE, "File IO error.");
	}

	return 0;
}


/*
 * Emit the pre-defined ASC functions.
 */
void emitPreDefs() {
	emitStmt(STMT_LEN, "");
	emitStmt(STMT_LEN, "");
	emitStmt(STMT_LEN, "");
	emitStmt(STMT_LEN, "");
	emitComment("#######################################################");
	emitStmt(STMT_LEN, "");
	emitStmt(STMT_LEN, "Pre-defined ASC functions to follow");
	emitStmt(STMT_LEN, "");
	emitComment("#######################################################");
	emitStmt(STMT_LEN, "");
	emitStmt(STMT_LEN, "");

	/* call to generated function in PreDefAsc.c */
	emitPreDefAsc();
}


/*
 * Emit anything that must be emitted before the code generated from the
 * input PAL. This includes predefined funcs and procs, constants, etc.
 */
void emitInit() {
	emitComment("ASC code generated by Yet Another CMPUT415 Compiler.");
	emitComment("May the Force be ever in your favour, Mr. Potter.");
	emitComment("CMPUT 415 - Fall 2013");
	emitStmt(STMT_LEN, "");
}

