/*
 * Module implementing writing generated ASC code to file.
 */
#include "EmitToFile.h"


/*
 * Write generated code to file.
 *
 * Parameters:
 * 	fileName: name of the .asc file to which to write.
 * Return:
 * 	0 on success,
 * 	non-zero otherwise
 */
int emitToFile(char *fileName) {
	FILE *ascfp = NULL;

	if (doNotEmit) {
		return 1;
	}

	/* open the file */
	ascfp = fopen(fileName, "w");

	/* 
	 * any pre-defined functions are already on stmts, as they are emitted
	 * in Init.c initialize().
	 */

	/* write the emitted code to file */
	writeStmtLL(ascfp, stmts);

	/* write end-of-file stuff */
	// TODO

	/* close the file */
	if (fclose(ascfp) != 0) {
		err(EXIT_FAILURE, "File IO error.");
	}

	return 0;
}


/*
 * Emit anything that must be emitted before the code generated from the
 * input PAL. This includes predefined funcs and procs, constants, etc.
 */
void emitInit() {
	emitComment("ASC code generated by Yet Another CMPUT415 Compiler.");
	emitComment("May the Force be ever in your favour, Mr. Potter.");
	emitComment("CMPUT 415 - Fall 2013");
	emitStmt(STMT_LEN, "");
}

